name: Run Il2CppDumper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Download Il2CppDumper
      run: |
        wget https://github.com/Perfare/Il2CppDumper/releases/download/v6.7.46/Il2CppDumper-net6-v6.7.46.zip
        unzip Il2CppDumper-net6-v6.7.46.zip -d dumper

    - name: Run Dumper Safe Mode
      run: |
        mkdir -p output
        cd dumper
        # Hata verse bile süreci durdurmayıp logları görelim
        dotnet Il2CppDumper.dll ../libil2cpp.so ../global-metadata.dat ../output || echo "Dumper uyarisi alindi"
        
        # Eğer dump.cs oluştuysa görelim
        ls -la ../output

    - name: Upload Dump Result
      uses: actions/upload-artifact@v4
      with:
        name: dump-result
        path: output/
