name: Run Il2CppDumper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Download Modded Dumper for Encrypted Metadata
      run: |
        # Şifreli metadata destekleyen güncel modlu sürümü çekiyoruz
        wget https://github.com/Krypton-Byte/Il2CppDumper/releases/download/v6.7.40-mod/Il2CppDumper.zip
        unzip Il2CppDumper.zip -d dumper

    - name: Run Bypass and Dump
      run: |
        mkdir -p output
        cd dumper
        dotnet Il2CppDumper.dll ../libil2cpp.so ../global-metadata.dat ../output || true
        cd ../output
        ls -la

    - name: Upload Dump Result
      uses: actions/upload-artifact@v4
      with:
        name: dump-result
        path: output/
