name: Run Il2CppDumper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build Il2CppDumper from Source
      run: |
        git clone https://github.com/Perfare/Il2CppDumper.git dumper_src
        cd dumper_src/Il2CppDumper
        dotnet publish -c Release -f net8.0 -r linux-x64 --self-contained true -o ../../compiled_dumper

    - name: Execute Dumper
      run: |
        mkdir -p output
        pwd
        ls -la
        ../../compiled_dumper/Il2CppDumper libil2cpp.so global-metadata.dat output
        ls -la output

    - name: Upload Dump Result
      uses: actions/upload-artifact@v4
      with:
        name: dump-result
        path: output/
